# The following variables can be overwritten
# variables:
# THEME_NAME: $CI_PROJECT_TITLE # default is the project name in gitlab
# THEME_SOURCE_DIR: '' # use 'src/' if it starts in the src dir
# DEV_IMAGE: shopware/development:7.4-composer-2
# MYSQL_IMAGE: 'mysql:5.7'
# MYSQL_CMD: 'mysqld' # use $MYSQL8_CMD for mysql >= 8
variables:
  THEME_NAME: "SwagCinemaTheme"
  PLATFORM_BRANCH: "6.4.7.0"

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/theme.yml'

.base_env_vars: &base_env_vars
  - export THEME_NAME="${THEME_NAME:-${CI_PROJECT_TITLE}}"

build zip:
  stage: build
  image:
    name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.3.1
    entrypoint: [ "" ]
  rules:
    - exists:
        - manifest.xml
  variables:
    DATABASE_URL: "mysql://root:root@database:3306/root?sslmode=disable&charset=utf8mb4"
    PROJECT_ROOT: /opt/shopware
    ADMIN_PATH: $CI_PROJECT_DIR/src/Administration/Resources/app/administration
    STOREFRONT_PATH: $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront
  before_script:
    - *base_env_vars
    - mkdir -p /opt/shopware/custom/apps || true
    - ln -s "$PWD" "/opt/shopware/custom/apps/$THEME_NAME"
    - /opt/shopware/bin/console system:install --drop-database --basic-setup --force
    - /opt/shopware/bin/console app:install --activate "$THEME_NAME"
  script:
    - /opt/shopware/bin/build-js.sh
    - rm -rf /opt/shopware/custom/apps/${THEME_NAME}/${THEME_SOURCE_DIR}Resources/app/storefront/node_modules || true
    - plugin-uploader ext:zip --strategy=plain -- "/opt/shopware/custom/apps/$THEME_NAME"
    - mkdir -p /fix_zip
    - mv *.zip /fix_zip
    - cd /fix_zip
    - unzip -q *.zip
    - rm *.zip
    - mv * $THEME_NAME # fix folder name
    - zip -q -r ${CI_PROJECT_DIR}/$THEME_NAME.zip $THEME_NAME/ # create new zip
    - cd ${CI_PROJECT_DIR}
    - '[[ -r "${THEME_NAME}.zip" ]] || (echo "failed to create zip. Please run ./bin/init $THEME_NAME" && exit 1)'
    - mv "${THEME_NAME}.zip" "${CI_PROJECT_DIR}/$THEME_NAME.zip"
  artifacts:
    name: '${CI_PROJECT_TITLE}.zip'
    paths:
      - '*.zip'
