variables:
  CYPRESS_SPEC: 'cypress/**/workflow/**/*.spec.js'
  PERCY_SPEC: 'cypress/**/visual/**/*.visual.spec.js'
  PLATFORM_BRANCH: "trunk"
  PERCY_TARGET_BRANCH: "main"
  PLUGIN_DEPENDENCIES:
    value: >
      [
         { "name": "SwagCustomizedProducts", "url": "gitlab.shopware.com/shopware/6/services/customized-product", "branch": "next-21258/6.5-compatibility" },
        # { "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" },
        # { "name": "SwagAmazonPay", "url": "gitlab.shopware.com/shopware/6/services/swagamazonpay", "branch": "master" },
         { "name": "SwagCmsExtensions", "url": "gitlab.shopware.com/shopware/6/services/cms-extensions", "branch": "master" }
      ]
    description: 'Plugin dependencies. Defined in json. Example: [{ "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" }]'
  COMPOSER_DEPENDENCIES:
    value: >
      [
        "theiconic/name-parser",
        "amzn/amazon-pay-api-sdk-php:2.2.1"
      ]
    description: 'Additional composer dependencies. Defined in json. Example: ["theiconic/name-parser", "amzn/amazon-pay-api-sdk-php:2.2.1"]'

build zip:
  stage: build
  # Revert after node is fixed in ghcr.io/friendsofshopware/platform-plugin-dev
  allow_failure: true
  image:
    name: ghcr.io/friendsofshopware/shopware-cli
    entrypoint: [ "" ]
  rules:
    - exists:
        - manifest.xml
  variables:
    DATABASE_URL: "mysql://root:root@database:3306/root?sslmode=disable&charset=utf8mb4"
    PROJECT_ROOT: /opt/shopware
    ADMIN_PATH: $CI_PROJECT_DIR/src/Administration/Resources/app/administration
    STOREFRONT_PATH: $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront
  before_script:
    - !reference [.base_env_vars]
  script:
    - shopware-cli extension zip . --disable-git --verbose
    - shopware-cli extension validate $THEME_NAME.zip
#  script:
#    - /opt/shopware/bin/build-js.sh
#    - rm -rf /opt/shopware/custom/apps/${THEME_NAME}/${THEME_SOURCE_DIR}Resources/app/storefront/node_modules || true
#    - plugin-uploader ext:zip --strategy=plain -- "/opt/shopware/custom/apps/$THEME_NAME"
#    - mkdir -p /fix_zip
#    - mv *.zip /fix_zip
#    - cd /fix_zip
#    - unzip -q *.zip
#    - rm *.zip
#    - mv * $THEME_NAME # fix folder name
#    - zip -q -r ${CI_PROJECT_DIR}/$THEME_NAME.zip $THEME_NAME/ # create new zip
#    - cd ${CI_PROJECT_DIR}
#    - '[[ -r "${THEME_NAME}.zip" ]] || (echo "failed to create zip. Please run ./bin/init $THEME_NAME" && exit 1)'
    - mv "${THEME_NAME}.zip" "${CI_PROJECT_DIR}/$THEME_NAME.zip"
  artifacts:
    name: '${CI_PROJECT_TITLE}.zip'
    paths:
      - '*.zip'

.base_install: &base_install
  - composer install -o --no-scripts
  - mkdir -p config/jwt || true
  - bin/console system:generate-jwt || true
  - bin/console system:install --drop-database --basic-setup --force >/dev/null
  - composer run init:js
  - composer run build:js
  - bin/console bundle:dump
  - bin/console feature:dump || true
#  - '(cd src/Administration/Resources/app/administration/ && npm ci && npm run build)'
#  - '(cd src/Storefront/Resources/app/storefront/ && npm ci && npm run production && node copy-to-vendor.js)'

.theme_install: &theme_install
  - bin/console app:refresh
  - bin/console app:activate $THEME_NAME
  - bin/console theme:change --all $THEME_NAME
  - bin/console assets:install
  - bin/console cache:clear

cypress:
  before_script:
    - export THEME_NAME="${THEME_NAME:-${CI_PROJECT_TITLE}}"
    - mv "$THEME_NAME.zip" /tmp/theme.zip
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git . --branch $PLATFORM_BRANCH
    - mkdir -p custom/apps || true
    - unzip -q /tmp/theme.zip -d custom/apps
    - *base_install
    - *theme_install
    - !reference [ .install_dependencies ]
    - SERVICE_PHPFPM_OPTS=--allow-to-run-as-root CONTAINER_UID=root /entrypoint supervisord > /dev/null 2>&1 &
    - bin/console e2e:dump-db
    - cd custom/apps/$THEME_NAME/${THEME_SOURCE_DIR}${E2E_PROJECT_PATH}
    - npm ci

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/theme.yml'
