variables:
    THEME_NAME: "SwagCinemaTheme"
    PLATFORM_BRANCH: "6.4.7.0"
    PLUGIN_DEPENDENCIES:
        value: >
            [{ "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" }]
        description: 'Plugin dependencies. Defined in json. Example: [{ "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" }]'

include:
    project: 'shopware/6/product/platform'
    ref: 'trunk'
    file: '.gitlab/templates/theme.yml'
