# The following variables can be overwritten
# variables:
    # THEME_NAME: $CI_PROJECT_TITLE # default is the project name in gitlab
    # THEME_SOURCE_DIR: '' # use 'src/' if it starts in the src dir
    # DEV_IMAGE: shopware/development:7.4-composer-2
    # MYSQL_IMAGE: 'mysql:5.7'
    # MYSQL_CMD: 'mysqld' # use $MYSQL8_CMD for mysql >= 8
variables:
  THEME_NAME: "SwagCinemaTheme"
  PLATFORM_BRANCH: "6.4.7.0"
  PAYPAL_PLUGIN_BRANCH: "master"

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/theme.yml'

.base_env_vars: &base_env_vars
    - export THEME_NAME="${THEME_NAME:-${CI_PROJECT_TITLE}}"

.base_install: &base_install
    - composer config --global allow-plugins.composer/package-versions-deprecated true
    - composer config --global allow-plugins.bamarni/composer-bin-plugin true
    - composer config --global allow-plugins.phpstan/extension-installer true
    - composer install
    - mkdir -p config/jwt || true
    - bin/console system:generate-jwt || true
    - bin/console system:install --drop-database --basic-setup --force >/dev/null
    - bin/console bundle:dump
    - chown -R application:application .
    - npm --prefix custom/plugins/SwagPayPal/src/Resources/app/storefront/ clean-install
    - bin/console plugin:refresh
    - bin/console plugin:install --activate SwagPayPal
    - '(cd src/Administration/Resources/app/administration/ && npm ci && npm run build)'
    - '(cd src/Storefront/Resources/app/storefront/ && npm ci && npm run production && node copy-to-vendor.js)'

.theme_install: &theme_install
    - bin/console app:install --activate $THEME_NAME
    - bin/console cache:clear
    - bin/console theme:change --all $THEME_NAME
    - bin/console assets:install

cypress:
    stage: E2E
    needs:
        - build zip
    rules:
        - exists:
              - Resources/app/storefront/test/e2e/cypress.json
              - src/Resources/app/storefront/test/e2e/cypress.json
    variables:
        GIT_STRATEGY: none
        E2E_PROJECT_PATH: Resources/app/storefront/test/e2e/
        APP_ENV: e2e
    before_script:
        - *base_env_vars
        - mv "$THEME_NAME.zip" /tmp/theme.zip
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git . --branch $PLATFORM_BRANCH
        - mkdir -p custom/apps || true
        - unzip -q /tmp/theme.zip -d custom/apps
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/services/paypal.git custom/plugins/SwagPayPal --branch $PAYPAL_PLUGIN_BRANCH
        - *base_install
        - *theme_install
        - /entrypoint supervisord > /dev/null 2>&1 &
        - bin/console e2e:dump-db
        - cd custom/apps/$THEME_NAME/${THEME_SOURCE_DIR}${E2E_PROJECT_PATH}
        - npm ci
    script:
        - ./node_modules/.bin/cypress run
            --browser $BROWSER
            --headless
            --env grep=visual,invert=1
    after_script:
        - *base_env_vars
        - cd custom/apps/$THEME_NAME/${THEME_SOURCE_DIR}${E2E_PROJECT_PATH}
        - mkdir $CI_PROJECT_DIR/var/log/e2e || true
        - mkdir -p cypress/mochareports || true
        - npx mochawesome-merge cypress/results/mocha/*.json > cypress/mochareports/report.json
        - npx marge cypress/mochareports/*.json -f report -o mochareports
        - mv cypress/results/single-reports/*.xml $CI_PROJECT_DIR/var/log/e2e/ || true
        - mv mochareports/ $CI_PROJECT_DIR/var/log/e2e/ || true
    artifacts:
        when: always
        paths:
            - var/log/*
        reports:
            junit: var/log/e2e/*.xml
