variables:
  CYPRESS_SPEC: 'cypress/**/workflow/**/*.spec.js'
  PERCY_SPEC: 'cypress/**/visual/**/*.visual.spec.js'
  PLATFORM_BRANCH: "trunk"
  PERCY_TARGET_BRANCH: "master"
  PLUGIN_DEPENDENCIES:
    value: >
      [
        # { "name": "SwagCustomizedProducts", "url": "gitlab.shopware.com/shopware/6/services/customized-product", "branch": "master" },
        # { "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" },
        # { "name": "SwagAmazonPay", "url": "gitlab.shopware.com/shopware/6/services/swagamazonpay", "branch": "master" },
        # { "name": "SwagCmsExtensions", "url": "gitlab.shopware.com/shopware/6/services/cms-extensions", "branch": "master" }
      ]
    description: 'Plugin dependencies. Defined in json. Example: [{ "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" }]'
  COMPOSER_DEPENDENCIES:
    value: >
      [
        "theiconic/name-parser",
        "amzn/amazon-pay-api-sdk-php:2.2.1"
      ]
    description: 'Additional composer dependencies. Defined in json. Example: ["theiconic/name-parser", "amzn/amazon-pay-api-sdk-php:2.2.1"]'
  FEATURE_ALL: 'major'
  v6_5_0_0: '1'

.base_install: &base_install
  - composer install -o --no-scripts
  - mkdir -p config/jwt || true
  - bin/console system:generate-jwt || true
  - bin/console system:install --drop-database --basic-setup --force >/dev/null
  - composer run init:js
  - composer run build:js
  - bin/console bundle:dump
  - bin/console feature:dump || true
#  - '(cd src/Administration/Resources/app/administration/ && npm ci && npm run build)'
#  - '(cd src/Storefront/Resources/app/storefront/ && npm ci && npm run production && node copy-to-vendor.js)'

cypress:
  before_script:
    - export THEME_NAME="${THEME_NAME:-${CI_PROJECT_TITLE}}"
    - mv "$THEME_NAME.zip" /tmp/theme.zip
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git . --branch $PLATFORM_BRANCH
    - mkdir -p custom/apps || true
    - unzip -q /tmp/theme.zip -d custom/apps
    - *base_install
    - !reference [ .theme_install ]
    - !reference [ .install_dependencies ]
    - SERVICE_PHPFPM_OPTS=--allow-to-run-as-root CONTAINER_UID=root /entrypoint supervisord > /dev/null 2>&1 &
    - bin/console e2e:dump-db
    - cd custom/apps/$THEME_NAME/${THEME_SOURCE_DIR}${E2E_PROJECT_PATH}
    - npm ci

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/theme.yml'
